# -*- coding: utf-8 -*-
{
    'name': 'Pragtech Jewellery Management',
    'version': '17.5',
    'category': 'Services',
    'author': 'Pragmatic TechSoft Pvt Ltd.',
    'website': 'pragtech.co.in',
    'summary': 'Pragtech Jewelry Management',
    'description': 'Pragtech Jewelry Management',
    'depends': ['product', 'stock', 'purchase', 'sale_management', 'mass_mailing', 'hr', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'data/product_data.xml',
        'report/sale_order_report.xml',
        'report/purchase_order_report.xml',
        'report/vendor_bill_report.xml',
        'report/delivery_slip.xml',
        'views/product_product.xml',
        'views/making_charge.xml',
        'views/purity.xml',
        'views/purchase_order.xml',
        'views/sale_order.xml',
        'views/sale_portal.xml',
        'views/purchase_portal.xml',
        'views/goldrate_perday.xml',
        'views/gold_rate_scheduler.xml',
        'views/menu.xml',
    ],
    'images': ['static/description/jewellery_management_banner.gif'],
    'live_test_url': 'http://www.pragtech.co.in/company/proposal-form.html?id=103&name=Pragtech-Jewelry-Management',
    'price': 99.00,
    'currency': 'USD',
    'license': 'OPL-1',
    'application': True,
    'auto_install': False,
    'installable': True,
}
